stages:
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-push-docker-image:
  stage: build
  # Specify a Docker image to run the job in.
  image: docker:dind
  # Specify an additional image 'docker:dind' ("Docker-in-Docker") that
  # will start up the Docker daemon when it is brought up by a runner.
  services:
    - docker:dind
  # docker login steps  
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - echo $CI_REGISTRY:$IMAGE_TAG
  rules:   
    - when: always


