build-job:
  stage: build 
  script:
    - echo "builds some image"
  rules:   
    - when: always

###comments for testing
deploy-qa:
  stage: deploy
  script: 
    - echo "deploys automatically when changes are pushed to any branch"
  rules:   
    - when: always
    
deploy-stag:
  stage: deploy
  script:
    - echo "this deploys when a merge request is created"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH == "main"

deploy-prod:
  stage: deploy
  script:
    - echo "deploys to prod when main branch is tagged"
  only:
    - tags

